### ISSUE TITLE
Engine Shrouds Not Able to Recolor

### ISSUE THREAD

**Issue by rp1-lox** [OnlyLightMatters/TURD-MH#11]
Hello, 
         I am attempting to recolor the Engine Plates, however even when switching to the "its all shiny" and "MH recolor" parts, there is no option to open the recoloring GUI. If there is a way to fix this, please let me know.

**Comment by rp1-lox** [comment]
Version: 1.12.9\
Actually, this issue seems to affect all BG/MH parts.

**Comment by OnlyLightMatters** [comment]
https://zupimages.net/up/23/02/xmty.png
Actually Works in 1.12.x. Check your install steps.
