### ISSUE TITLE
Chrome colour doesn't reflect some things (explained)

### ISSUE THREAD

**Issue by ghost** [OnlyLightMatters/TURD-MH#12]
CLOUDS 
As u can see, there are not clouds in the reflections at ground altitude. Ground elements are reflected correctly.
https://i.imgur.com/3aNLk6s.png
85.000m
https://i.imgur.com/OUVca5G.png
120.000m
https://i.imgur.com/7YVFYNK.png

Noticed that in this distance, kerbin does a fast flickering when moving camera, which is possible to be related.
160.000m? Flickering (i think it's reloading kerbin textures, but not sure why)
https://i.imgur.com/lmWywon.png
159.993m (camera near planet)
https://i.imgur.com/CDu0ok3.png
159.993m (camera far from planet)
https://i.imgur.com/Q9ZOZuY.png

200.000m (all good)
https://i.imgur.com/chLfSNS.png

KERBAL AND VESSEL
It's not reflecting the own vessel or kerbals in EVA in any of the cases exposed here.

Using 2048 reflection texture and update each frame

**Comment by OnlyLightMatters** [comment]
1/ These are not MH or BG parts
2/ This is likely related to the core textures unlimited mod and I am not sure it was planned to implement this feature from the beginning
